### ISSUE TITLE
$remoteport = bash.exe -c "ip addr show eth0 | grep 'inet '"

### ISSUE THREAD

**Issue by falseUtopia** [snowphone/WSL2-port-forwarding-guide#1]
$remoteport = bash.exe -c "ip addr show eth0 | grep 'inet '"

不需要下载 net-tools

**Comment by junoh-moon** [comment]
So, if I understand correctly, `ifconfig` is replaced by `ip` in modern debian systems?

**Comment by falseUtopia** [comment]
> So, if I understand correctly, `ifconfig` is replaced by `ip` in modern debian systems?

我随便搜的 ,你可以看下  https://linux.cn/article-4326-1.html

wsl Ubuntu 没有预装 net-tools
